import { EmotionKey, EmotionMeta } from '../types';

export const EMOTIONS: EmotionMeta[] = [
  {
    key: 'radiant',
    label: 'Muito Feliz',
    childDescription: 'Meu coração está cheio de luz e alegria!',
    emoji: '☀️',
    colorBg: 'bg-amber-50 hover:bg-amber-100',
    colorBorder: 'border-amber-200 focus:border-amber-400',
    colorText: 'text-amber-800',
    severity: 'low',
  },
  {
    key: 'calm',
    label: 'Tranquilo & Calminho',
    childDescription: 'Estou em paz, como uma folhinha boiando na água.',
    emoji: '🌿',
    colorBg: 'bg-emerald-50 hover:bg-emerald-100',
    colorBorder: 'border-emerald-200 focus:border-emerald-400',
    colorText: 'text-emerald-800',
    severity: 'low',
  },
  {
    key: 'tired',
    label: 'Sem Energia / Cansadinho',
    childDescription: 'Parece que minha bateria acabou e o corpo pesa.',
    emoji: '☁️',
    colorBg: 'bg-sky-50 hover:bg-sky-100',
    colorBorder: 'border-sky-200 focus:border-sky-400',
    colorText: 'text-sky-800',
    severity: 'medium',
  },
  {
    key: 'scared',
    label: 'Com Medo / Inseguro',
    childDescription: 'Sinto frio na barriga e borboletas assustadas.',
    emoji: '🦔',
    colorBg: 'bg-indigo-50 hover:bg-indigo-100',
    colorBorder: 'border-indigo-200 focus:border-indigo-400',
    colorText: 'text-indigo-800',
    severity: 'medium',
  },
  {
    key: 'angry',
    label: 'Bravo / Como um Vulcão',
    childDescription: 'Dá vontade de explodir de raiva por dentro.',
    emoji: '🌋',
    colorBg: 'bg-rose-50 hover:bg-rose-100',
    colorBorder: 'border-rose-200 focus:border-rose-400',
    colorText: 'text-rose-800',
    severity: 'medium',
  },
  {
    key: 'sad',
    label: 'Coração Apertado / Triste',
    childDescription: 'Sinto vontade de chorar e um peso no peito.',
    emoji: '🌧️',
    colorBg: 'bg-blue-50 hover:bg-blue-100',
    colorBorder: 'border-blue-200 focus:border-blue-400',
    colorText: 'text-blue-800',
    severity: 'high',
  },
  {
    key: 'critical',
    label: 'Machucado por Dentro / Querendo Sumir',
    childDescription: 'Está doendo demais e não quero mais sentir essa dor.',
    emoji: '🩹',
    colorBg: 'bg-purple-50 hover:bg-purple-100',
    colorBorder: 'border-purple-300 ring-2 ring-purple-200',
    colorText: 'text-purple-900',
    severity: 'critical',
  },
];

export const BODY_SENSATIONS = [
  { id: 'heart', label: 'Coração acelerado', icon: '💓' },
  { id: 'throat', label: 'Nó na garganta', icon: '🧣' },
  { id: 'belly', label: 'Frio na barriga', icon: '🦋' },
  { id: 'head', label: 'Cabeça cheia / pesada', icon: '🌪️' },
  { id: 'body_heavy', label: 'Corpo sem forças', icon: '🪨' },
  { id: 'shivering', label: 'Mãos tremendo', icon: '🍃' },
  { id: 'calm_body', label: 'Corpo relaxado e quentinho', icon: '🧸' },
];

export const CONTEXT_TAGS = [
  'Escola / Tarefas',
  'Família em casa',
  'Amigos e colegas',
  'Brincadeiras',
  'Pesadelo ou noite',
  'Sentimento de solidão',
  'Não sei explicar bem',
];
